#!/usr/bin/expect -f
set password "Frappe@Hrms!"
spawn ssh -o StrictHostKeyChecking=no root@103.192.198.227 "cd /home/frappe/frappe-bench && echo \"frappe.delete_doc('Branches', 'Dewas', ignore_missing=True, force=True); frappe.delete_doc('Branches', 'Indore', ignore_missing=True, force=True); frappe.db.commit(); print('DONE_DELETION')\" | bench --site aas.com console"
expect "password:"
send "$password\r"
expect eof
